### ISSUE TITLE
convert コマンドには -strip オプションをつけるといいよ

### ISSUE THREAD

**Issue by yuitest** [aoisensi/aoisensi#1]
普通に ImageMagick を使うと、画像に埋め込まれたタイムスタンプが更新されちゃうから、差分が出ちゃうんだ。

そうするとこのコミット https://github.com/aoisensi/aoisensi/commit/5b205131cb029a874f3254846a17e8aa25184bcc みたいに、実際の画像に変化がないのに検出される、ということが増えてしまうよ。

そういうときのために [-strip](https://www.imagemagick.org/script/command-line-options.php#strip) オプションがあるよ。
これをつけると画像のいろいろなメタ情報を含めずに済むから、以降の操作は何度繰り返してもおなじ (冪等) になる、というわけさ。

**Comment by aoisensi** [comment]
😍 https://github.com/aoisensi/aoisensi/commit/091b29492dc542e05a4a87f02b5bce4517e7a31a
でもdateが消せない…

**Comment by yuitest** [comment]
うーん。これと同じ症状かな ?

> Debian (libpng 1.2.50) の環境では、これらの方法だとtIMEチャンクが残ってしまったので、以下のようにすると取り除くことができました。

http://qiita.com/orangain/items/b23df328881f6a9aa4e8

**Comment by yuitest** [comment]
すまんね、なまやけな解決手段を提示してしまってたぜ！

**Comment by aoisensi** [comment]
http://www.imagemagick.org/discourse-server/viewtopic.php?t=21711
ここにあったけどうまく動かなかった

**Comment by yuitest** [comment]
むむむっ

**Comment by yuitest** [comment]
`-strip -define png:exclude-chunk=tEXt,zTXt` でどうでしょ

**Comment by aoisensi** [comment]
そもそもdateチャンクが消えないんですよね
Ubuntuのバイナリが悪さしてる可能性が

**Comment by yuitest** [comment]
くっくやしい……！ちなみに Ubuntu のバージョンは？たぶん ImageMagick は APT で入るやつだよね。

**Comment by aoisensi** [comment]
aptからですね 16.04使ってます

**Comment by aoisensi** [comment]
docker...

**Comment by yuitest** [comment]
うっしゃーやってみるぜ

**Comment by yuitest** [comment]
Docker で Ubuntu 16.04 で試したところ

`-strip -define png:exclude-chunk=tEXt,zTXt,tIME` で行けるっぽいよ

オプションつけてない状態で作ったファイルに `strings` してみるとわかるけど `date:modify` と `date:create` は、チャンク自体は `zTXt` だから `exclude-chunk=date` では消えない。

**Comment by yuitest** [comment]
libpng のチャンクについては [ここに解説](http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html) がある。

**Comment by aoisensi** [comment]
https://github.com/aoisensi/aoisensi/commit/900057cb3983aa59cdd1a523f6338672254d70c5
Done!!

**Comment by aoisensi** [comment]
一秒たたずにクラッカーなったのこわ

**Comment by yuitest** [comment]
まじ唐突な Issue ですまんかった。ありがとうね！

**Comment by aoisensi** [comment]
こちらこそ！
